name: Compila e substitui os Componentes

on:
  workflow_dispatch:

jobs:
  compare-json:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Baixa o Arduino-lib-builder
      run: | 
        rm -rf ./tools/sdk/*
        cd ~
        git clone https://github.com/bmorcelli/esp32-arduino-lib-builder.git
        cd esp32-arduino-lib-builder
        git branch -r
        git checkout -b release/v4.4b origin/release/v4.4b
        git pull origin release/v4.4b
        
    - name: Instala os pré-requisitos
      run: bash ~/esp32-arduino-lib-builder/tools/prepare-ci.sh
      
    - name: Build Libs for esp32
      run: |
        cd ~/esp32-arduino-lib-builder
        bash ./build.sh -I 'release/v4.4d' -A 'idf-release/v4.4d' -c '/home/runner/work/arduino-esp32/arduino-esp32/'

    - name: Set up Git
      run: |
        rm ./tools/sdk/esp32/lib/libnet80211.a
        rm ./tools/sdk/esp32s3/lib/libnet80211.a
        cp ./deauth_patched_files/ESP32-lib/libnet80211.a ./tools/sdk/esp32/lib/
        cp ./deauth_patched_files/ESP32s3-lib/libnet80211.a ./tools/sdk/esp32s3/lib/
        
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"
        
    - name: Commit new components
      id: compare
      run: |
        git add .
        git commit -m "Components Update"
        git push
